# This file was generated by GoReleaser. DO NOT EDIT.
cask "topf" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "a44e790fba0d815f95928e98ec4e478b72263e057193152c32a5407b1ebd87c3"
      url "https://github.com/postfinance/topf/releases/download/v#{version}/topf_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d06541e1051e7390f5541d6d0ed7b3b01606a0c971946cbb156d780fe03b2a1d"
      url "https://github.com/postfinance/topf/releases/download/v#{version}/topf_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0e924d8b282c1baaca39edded14dd3582c4b55c6e990a760c3c1b7b86eb7ac42"
      url "https://github.com/postfinance/topf/releases/download/v#{version}/topf_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f525a48fd17dfa23e96bb476ceddd57c8b78d77f8e8d1e90ae468e2240bb59ec"
      url "https://github.com/postfinance/topf/releases/download/v#{version}/topf_linux_arm64.tar.gz"
    end
  end

  name "topf"
  desc "Talos Orchestrator by PostFinance"
  homepage "https://github.com/postfinance/topf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "topf"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/topf"]
    end
  end

  # No zap stanza required

end
