# This file was generated by GoReleaser. DO NOT EDIT.
cask "topf" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "0dfe3848fa63bcd7382f9b069afb650ec99586abc6e56614c17f3d46dd4abe27"
      url "https://github.com/postfinance/topf/releases/download/v#{version}/topf_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "28b1ac0d0393ae1ac465393ef7aae5cceb633291426e276baa7e7c3520afb2ab"
      url "https://github.com/postfinance/topf/releases/download/v#{version}/topf_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "553504ea309656db54ca592afe732e36cde76ec72383b0a616158a6d8dcfe612"
      url "https://github.com/postfinance/topf/releases/download/v#{version}/topf_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a9bb560a4e8af6fcd3f2843e594eeaa6c94cc398c4c962d003913711bc49a19a"
      url "https://github.com/postfinance/topf/releases/download/v#{version}/topf_linux_arm64.tar.gz"
    end
  end

  name "topf"
  desc "Talos Orchestrator by PostFinance"
  homepage "https://github.com/postfinance/topf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "topf"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/topf"]
    end
  end

  # No zap stanza required

end
