# This file was generated by GoReleaser. DO NOT EDIT.
cask "topf" do
  version "0.2.2"

  on_macos do
    on_intel do
      url "https://github.com/postfinance/topf/releases/download/v#{version}/topf_darwin_amd64.tar.gz"
      sha256 "db9a704615ad612fb5bf29194d6c58773ce0eda5739a29841e44428b7dcf8841"
    end
    on_arm do
      url "https://github.com/postfinance/topf/releases/download/v#{version}/topf_darwin_arm64.tar.gz"
      sha256 "9596889a6f18ecb0261998922d1cf6aa67eb76a85e1a1385b581dac8e740b7c6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/postfinance/topf/releases/download/v#{version}/topf_linux_amd64.tar.gz"
      sha256 "0cafc7b0042a319a117a961fc893e9ecc4488ff3a5464e7ff07c88e68a403d46"
    end
    on_arm do
      url "https://github.com/postfinance/topf/releases/download/v#{version}/topf_linux_arm64.tar.gz"
      sha256 "454c065fc6596658c5eb519e174b4f5d83cb1d60bb6dbcc8289469cd08d94e6d"
    end
  end

  name "topf"
  desc "Talos Orchestrator by PostFinance"
  homepage "https://github.com/postfinance/topf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "topf"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/topf"]
    end
  end

  # No zap stanza required

end
